name: Build Android ROM

on:
  workflow_dispatch:

jobs:
  build-rom:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
        # That's it! Now use your normal steps

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 24

      - name: Set up environment
        run: |
          sudo apt update && sudo apt install -y \
          bc bison python-is-python3 libwxgtk3.0-gtk3-dev build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick libncurses5 lib32readline-dev lib32z1-dev libelf-dev liblz4-tool lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          sudo add-apt-repository universe

      - name: Install repo
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Initialize repo
        run: |
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          ccache -M 70G
          ccache -o compression=true
          MANIFEST_BRANCH="17.1"
          mkdir workspace
          cd workspace
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git lfs install
          repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-${MANIFEST_BRANCH} --git-lfs --no-clone-bundle

      - name: Sync source for LineageOS
        run: repo sync -c -j$(nproc --all)
        working-directory: workspace

      - name: Clone device, kernel, and vendor
        run: |
          DEVICE_TREE_URL="https://github.com/TeamWin/android_device_motorola_pettyl"
          KERNEL_URL="https://github.com/MotorolaMobilityLLC/kernel-msm"
          VENDOR_URL="https://github.com/AndroidBlobs/vendor_motorola_pettyl"

          DEVICE_TREE_BRANCH="android-8.1"
          KERNEL_BRANCH="android-10-release-qpzs30.30-q3-38-69-10"
          VENDOR_BRANCH="8-OPGS28.54-53-8-7-0814d-release-keys"

          # Clonar repositórios com os branches específicos
          git clone -b $DEVICE_TREE_BRANCH $DEVICE_TREE_URL workspace/device/motorola/pettyl
          git clone -b $KERNEL_BRANCH $KERNEL_URL workspace/kernel/motorola/pettyl
          git clone -b $VENDOR_BRANCH $VENDOR_URL workspace/vendor/motorola/pettyl
        working-directory: workspace

      - name: Sync ROM dependencies
        run: |
          source build/envsetup.sh
          breakfast pettyl
        working-directory: workspace

      - name: Build ROM
        run: |
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          croot
          brunch bacon
        working-directory: workspace

      - name: Upload to Release
        uses: actions/upload-artifact@v3
        with:
          name: ROM-pettyl-17.1
          path: workspace/out/target/product/pettyl/*.zip
